version: '3'

services:
  app:
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
      context: .
    depends_on:
      - database
      - nginx
    env_file:
      - .env
      - .env.local
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
